version: '3.3'
services:
    db:
        image: mariadb
        command: mysqld --character-set-serve=utf8mb4 --collation-server=utf8mb4_unicode_ci
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=db
            - MYSQL_USER=django
            - MYSQL_PASSWORD=password
        ports:
            - '3306:3306'
        volumes:
            -   type: bind
                source: ./docker/db/var/lib/mysql
                target: /var/lib/mysql
    localstack:
        image: localstack/localstack
        ports:
            - '4567-4584:4567-4584'
            - '8888:8888'
        environment:
            - PORT_WEB_UI=8888
    web:
        build:
            context: .
            dockerfile: ./docker/web/Dockerfile
        command: sh -c './bin/wait-for-it.sh db:3306 -t 60; ./bin/entrypoint.local.sh'
        environment:
            - AWS_ACCESS_KEY_ID=AKIAIOSFODNN7EXAMPLE
            - AWS_SECRET_ACCESS_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
            - AWS_DEFAULT_REGION=ap-northeast-1
            - DJANGO_SECRET_KEY=dev
            - DEBUG=true
            - MYSQL_DATABASE=db
            - MYSQL_USER=django
            - MYSQL_PASSWORD=password
            - RELEASE_STAGE=development
        volumes:
            -   type: bind
                source: ./src
                target: /src
        ports:
            - '8080:8080'
        depends_on:
            - db
            - localstack
    nginx:
        image: nginx
        restart: always
        ports:
            - '80:80'
        volumes:
            -   type: bind
                source: ./docker/nginx/etc/nginx
                target: /etc/nginx
            -   type: bind
                source: ./src/collected_static
                target: /var/www/collected_static
        depends_on:
            - web
