version: '3.3'
services:
    web:
        build:
            context: .
            dockerfile: ./docker/web/Dockerfile
        command: sh -c './bin/entrypoint.sh'
        env_file:
            - .env.db
            - .env.web
        volumes:
            - type: bind
              source: ./src
              target: /src
        ports:
            - '8080:8080'
        logging: &logging
            driver: "awslogs"
            options:
                awslogs-region: ${AWSLOGS_REGION}
                awslogs-group: ${AWSLOGS_GROUP}
                tag: '{{ with split .ImageName ":" }}{{join . "_"}}{{end}}'
                awslogs-create-group: "true"
        logging:
            <<: *logging
    nginx:
        image: nginx
        restart: always
        ports:
            - '80:80'
        volumes:
            - type: bind
              source: ./docker/nginx/etc/nginx
              target: /etc/nginx
            - type: bind
              source: ./src/static
              target: /var/www/static
        depends_on:
            - web
        logging:
            <<: *logging
