version: '3.3'
services:
    localstack:
        image: localstack/localstack
        ports:
            - '4567-4584:4567-4584'
            - '8888:8888'
        environment:
            - PORT_WEB_UI=8888
            - DATA_DIR=/tmp/localstack
        volumes:
            - localstack_data:/tmp/localstack
    db:
        image: mariadb
        command: mysqld --character-set-serve=utf8mb4 --collation-server=utf8mb4_unicode_ci
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=db
            - MYSQL_PASSWORD=password
            - MYSQL_USER=django
        ports:
            - '3306:3306'
        volumes:
            - db_data:/var/lib/mysql
    web:
        build:
            context: .
            dockerfile: ./docker/web/Dockerfile
        command: sh -c './bin/wait-for-it.sh db:3306 -t 30; ./bin/entrypoint.local.sh'
        environment:
            - AWS_ACCESS_KEY_ID=AKIAIOSFODNN7EXAMPLE
            - AWS_SECRET_ACCESS_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
            - AWS_DEFAULT_REGION=ap-northeast-1
            - DEBUG=true
            - DJANGO_SECRET_KEY=dev
            - MYSQL_DATABASE=db
            - MYSQL_PASSWORD=password
            - MYSQL_USER=django
            - RELEASE_STAGE=development
        volumes:
            - ./src:/src
            - collected_static:/src/collected_static
        ports:
            - '8080:8080'
        depends_on:
            - localstack
            - db
    nginx:
        build:
            context: nginx
            dockerfile: Dockerfile
        restart: always
        ports:
            - '80:80'
        volumes:
            - collected_static:/var/www/collected_static
        depends_on:
            - web
volumes:
    db_data:
        driver: local
    localstack_data:
        driver: local
    collected_static:
