version: '3.3'
services:
    db:
        image: mariadb
        command: mysqld --character-set-serve=utf8mb4 --collation-server=utf8mb4_unicode_ci
        env_file: .env.db
        ports:
            - '3306:3306'
        volumes:
            - type: bind
              source: ./docker/db/var/lib/mysql
              target: /var/lib/mysql
        logging: &logging
            driver: "awslogs"
            options:
                awslogs-region: ${AWSLOGS_REGION}
                awslogs-group: ${AWSLOGS_GROUP}
                tag: '{{ with split .ImageName ":" }}{{join . "_"}}{{end}}'
                awslogs-create-group: "true"
    web:
        build:
            context: .
            dockerfile: ./docker/web/Dockerfile
        command: sh -c './bin/wait-for-it.sh db:3306; ./bin/entrypoint.sh'
        env_file:
            - .env.db
            - .env.web
        volumes:
            - type: bind
              source: ./src
              target: /src
        ports:
            - '8080:8080'
        depends_on:
            - db
        logging:
            <<: *logging
    nginx:
        image: nginx
        restart: always
        ports:
            - '80:80'
        volumes:
            - type: bind
              source: ./docker/nginx/etc/nginx
              target: /etc/nginx
            - type: bind
              source: ./src/collected_static
              target: /var/www/collected_static
        depends_on:
            - web
        logging:
            <<: *logging
