# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/python:3.6
    environment:
      AWS_ACCESS_KEY_ID: "AKIAIOSFODNN7EXAMPLE"
      AWS_SECRET_ACCESS_KEY: "wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"
      DJANGO_SECRET_KEY: "test"
      PIPENV_PIPFILE: "web/src/Pipfile"
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-pip-dependencies-{{ checksum "web/src/Pipfile.lock" }}
            - v2-pip-dependencies-
      - run:
          name: Install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pipenv install --dev --system
      - save_cache:
          key: v2-pip-dependencies-{{ checksum "web/src/Pipfile.lock" }}
          paths:
            - venv
      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            cd web/src/
            python manage.py test
